### ISSUE TITLE
Switch datasets entirely

### ISSUE THREAD

**Issue by mwleeds** [CodeforBirmingham/Open-Disclosure#101]
Unless someone has a better idea, we're going to switch to FollowTheMoney.org's data and abandon all the data processing work we've done. It's much higher quality and integrating it into our existing data would be a pain. It's from the same source anyway. Hopefully it won't change our data model / API too much.

**Comment by Taitrnator** [comment]
:+1:

**Comment by davidgrieser** [comment]
I'm glad we have a 1.0 release that can just be hooked into and changed. :+1:

**Comment by tarifhaque** [comment]
@mleeds95 I don't think we should kill the backend you've made. There's definitely value in presenting data directly from the primary source (Alabama's public campaign finance disclosure website). So instead I think we should think of powerful and beautiful ways to combine data from FollowTheMoney and what we've already got. 

It would probably be useful to divide our UI for different audiences: one for analysts who want to 'dig deep' and one for the general citizen. FollowTheMoney's data can be easily manipulated to create pretty data vis for general audiences, but for people who want to look deeply at transactions and contributions, we should probably draw from the primary source.

**Comment by davidgrieser** [comment]
@tarifhaque You bring up a good point. I suppose I should have read and been more careful about the *abandon all the data processing* that we already have. To me I was assuming that we would stop using that API data stream and use the other. We should be able to do, what you were suggesting and provide multiple views or allow the user to change the data source. So we would end up just writing another API consumer and swap it in, then possibly make it a dropdown.
