### ISSUE TITLE
Use Grano for data visualizations 

### ISSUE THREAD

**Issue by Taitrnator** [CodeforBirmingham/Open-Disclosure#102]
http://granoproject.org/docs/
pacs drawing lines to donations

blue dots are dems, reds are GOP 
pacs interest group colors? (shade between red and blue?) 

size based on how much money. 

feel free to add to this

**Comment by tarifhaque** [comment]
This looks cool. But what functionality can Grano provide that our AngularJS + D3 front-end can't?

**Comment by mleeds95** [comment]
Yeah I don't think it does anything for us since we already have a backend.
