### ISSUE TITLE
images for candidates 

### ISSUE THREAD

**Issue by Taitrnator** [CodeforBirmingham/Open-Disclosure#110]
use something similar to google civic api to pull images for candidates and add them to data.

**Comment by mleeds95** [comment]
@Taitrnator we already have this: https://github.com/CodeforBirmingham/Open-Disclosure/blob/master/utils/CallCivicInfoAPI.py#L276

**Comment by mleeds95** [comment]
I added a call to CallSunlightAPI.py to our script on the backend.
