### ISSUE TITLE
Automate Download of Transaction CSV Files

### ISSUE THREAD

**Issue by cfilby** [CodeforBirmingham/Open-Disclosure#49]
Write a Python Script to fetch the Expenditure/InKind/Cash/OtherReceipts CSV files.

**Comment by cfilby** [comment]
Matthew may want to verify this is all working correctly and behaves as expected.

**Comment by mleeds95** [comment]
Worked great when I ran it. I'll do some more testing at some point to make sure all the other scripts handle the unedited data well.
