### ISSUE TITLE
Configure scripts to handle updating

### ISSUE THREAD

**Issue by mleeds95** [CodeforBirmingham/Open-Disclosure#55]
When we download new data we need to ensure we only process records that aren't already in our database and update those.

**Comment by agrueneberg** [comment]
Much appreciated, @mleeds95! Will start the cronjob to update the datasets later today.

**Comment by agrueneberg** [comment]
I just noticed that we need this for the districts as well. For now I'm just disabling the upload, don't expect a whole not of new ones popping up.

**Comment by agrueneberg** [comment]
Also, it doesn't seem to be working?
```
>> Loaded 20632 records from data/2015_Transactees.json
>> Number of errors = 0
>> Rows deleted  = 0
>> Rows updated = 0
>> Rows created = 20632
>> Loaded 30533 records from data/2015_Transactions.json
>> Number of errors = 0
>> Rows deleted  = 0
>> Rows updated = 0
>> Rows created = 30533
```

**Comment by agrueneberg** [comment]
Transaction was my bad: I forgot to add `id` as a row ID in Socrata. But Transactees is still duplicating.

**Comment by agrueneberg** [comment]
Found the problem: extracting the `transaction_ids` from the previous dataset didn't work if the dataset ran through the flatten target. Pushed a hackish fix in bf870b2091278a6aca28511132d4f84eb5969976, there is probably a more Pythonic way to parse a string of text into an array than using JSON.

**Comment by agrueneberg** [comment]
The district problem remains, but like I said, I don't think it's urgent.

**Comment by mleeds95** [comment]
I don't understand why we would want to do this for Districts. The OCD IDs should be static. If a district somehow goes away, I guess we want to keep it in our database so the old records make sense?

**Comment by agrueneberg** [comment]
Yes, I'll just use `ocdID` as row identifier. That'll solve the update problem in a natural way.
