### ISSUE TITLE
Write Python interface for Socrata

### ISSUE THREAD

**Issue by mleeds95** [CodeforBirmingham/Open-Disclosure#58]
Nathan said he will write a Python3 library to interface with Socrata's API.

**Comment by agrueneberg** [comment]
There is no official SDK for Python yet, but this looks promising: https://github.com/xmunoz/sodapy

**Comment by mleeds95** [comment]
Great, thanks for finding that. It looks like it's for Python 2 but that shouldn't be much of an issue. Hopefully @ntmcminn sees this.

**Comment by ntmcminn** [comment]
Nice!  Thanks for the pointer.
