### ISSUE TITLE
Set up cron jobs on server.

### ISSUE THREAD

**Issue by mleeds95** [CodeforBirmingham/Open-Disclosure#61]
We need cron jobs to download data, process it, and upload it to Socrata.

**Comment by agrueneberg** [comment]
How often do we want to run the pipeline? Every day? Once a week?

**Comment by mleeds95** [comment]
I think daily in the middle of the night would make sense. I believe that's how often the FCPA dumps its tables.

**Comment by davidgrieser** [comment]
If we can find the time that this is updated at night, we could load right after they do.

**Comment by mleeds95** [comment]
Both times I've looked at it recently it's been 12:30ish, so maybe 1 would be good.

**Comment by agrueneberg** [comment]
Let's give them some buffer and do 1 AM EDT (the server is in NYC).

**Comment by agrueneberg** [comment]
Done: `0 1 * * * make -C ~/repo/utils download organize flatten upload`
