### ISSUE TITLE
Write script to upload data to Socrata.

### ISSUE THREAD

**Issue by mleeds95** [CodeforBirmingham/Open-Disclosure#62]
We need to be able to automatically upload our data to Socrata. https://github.com/xmunoz/sodapy might be useful.

**Comment by agrueneberg** [comment]
Sorry that I have to ask again, @mleeds95, but which files are the ones that we would like to see on Socrata?

**Comment by mleeds95** [comment]
Parties, Transactees, Transactions, and Districts

**Comment by agrueneberg** [comment]
Thanks! Is there a reason why only the `GenerateDistricts` script outputs CSV by default?

**Comment by mleeds95** [comment]
I think just because that data is flat. We should probably make them all
JSON if that works for Socrata.

**Comment by mleeds95** [comment]
Maybe we should remove the CSV functionality altogether since it would break the Transactions one anyway when it tries to read the Transactees.

**Comment by agrueneberg** [comment]
Socrata only imports CSV, afaik.

**Comment by agrueneberg** [comment]
Nevermind, the API seems to accept JSON. Let me test this and I'll get back to you.

**Comment by agrueneberg** [comment]
I have created empty stubs for the datasets:
- Parties: [kjgr-g56d](https://brigades.opendatanetwork.com/resource/kjgr-g56d)
- Transactions: [vcap-yyfq](https://brigades.opendatanetwork.com/resource/vcap-yyfq)
- Transactees: [9xmj-xdkh](https://brigades.opendatanetwork.com/resource/9xmj-xdkh)
- Districts: [p8kt-epji](https://brigades.opendatanetwork.com/resource/p8kt-epji)

**Comment by agrueneberg** [comment]
I just tried to import the JSON datasets into the empty tables and the result is kind of surprising: we got all the rows, but they are all empty. I guess we have to create the schema in Socrata first and then upload.

**Comment by mleeds95** [comment]
That is pretty odd. Did you do it manually or with a script?

**Comment by mleeds95** [comment]
Accomplished with fe277f24cc3e97f9b751524ed061d50a850331b7
