### ISSUE TITLE
Move frontend stuff into gh-pages branch.

### ISSUE THREAD

**Issue by mleeds95** [CodeforBirmingham/Open-Disclosure#64]
Currently we're thinking we will let GitHub Pages host the site, so we need to set that up.

**Comment by mleeds95** [comment]
Tried this but I'm not familiar enough with bower/grunt/ruby/jekyll to configure it correctly.

**Comment by agrueneberg** [comment]
That's a good start :) http://www.codeforbirmingham.org/Open-Disclosure/ We will have to commit the Bower components in order for it to work, though.

**Comment by agrueneberg** [comment]
I uploaded the Bower components. @Taitrnator, please do your changes in this branch now (i.e. always run `git pull origin gh-pages` and `git push origin gh-pages`).

**Comment by agrueneberg** [comment]
@mleeds95 What's in `extras`? Shouldn't that be in `master`?

**Comment by mleeds95** [comment]
@agrueneberg I didn't realize that had been commited. It was just stuff I was keeping in my local repo.

**Comment by agrueneberg** [comment]
@mleeds95 Oh, I see. Looked useful, though! :)
