### ISSUE TITLE
Switching gears (needs to be broken down into sub-issues if we find consensus) 

### ISSUE THREAD

**Issue by Taitrnator** [CodeforBirmingham/Open-Disclosure#68]
So I think the initial source http://www.sos.state.al.us/vb/inquiry/inquiry.aspx?area=Campaign%20Finance is a useful primary source but equally un-useful. 

Right now the purpose of Open Disclosure: 
"The goal of the Open Disclosure project is to provide an easy to use web interface for Alabama's publicly available campaign finance data. This will empower citizens to better understand the flow of money in their political system, and consequently allow them to hold their representatives more accountable."

In order to "better understand the flow of money in [the] political system" 

The first primary emphasis should be on limiting our contribution data to state representatives. Also, we should track PAC and individual contributions to justices since were one of the handful of states that elects them. Lastly, we need to get data on representatives at the federal level, which I think we're lacking currently. Sunlight has some APIs for this if needed. Also, for a bigger sense of the picture, we can use <a href="http://www.followthemoney.org/election-overview?s=AL&y=2012"> Follow the Money API </a> which has made some extensive tags and associations. 

Another emphasis should be on dark money, or 501(c)4s who do not directly donate to candidates but have a huge impact on local elections by buying ads. A good source would be <a href="https://www.opensecrets.org/outsidespending/nonprof_elec.php">Open Secrets. </a> They have an extensive API for tracking this sort of spending. Additionally, each candidate's card should indicate what percentage of their funds include dark money. 

In order to "hold representatives more accountable" : 

A final emphasis should be on how this money shapes decision making in these positions. Sunlights APIs can be used extensively here. More specifically, <a href="http://sunlightlabs.github.io/openstates-api/">Open States API </a> as well as <a href="https://sunlightlabs.github.io/congress/"> Congress API </a>

So I think we can collect this data and gain a much better sense of the big picture with all of this taken into account. If sucessful, we can make something that associates categorized donations with political decision making. In addition, we can show how dark money shapes elections in Alabama. Also, since that data is also tagged by category for Open Secrets, we could make similar associations. 

Please comment, and lets all meet soon and discuss this. While its ambitious, I also think it could simplify steps moving forward and produce a much more effective tool for us.

**Comment by mleeds95** [comment]
I agree that we should add more data sources although we should be careful about what conclusions we draw for people (is there a specific definition of what constitutes dark money?).

**Comment by Taitrnator** [comment]
money contributed by 501(c)4s, on behalf on candidates, so not direct contributions persay. This kind of spending is very loosely governed but highly influential. Open Secrets keeps better track of this sort of spending.

**Comment by tarifhaque** [comment]
The National Institute on Money in State Politics (<a href="http://www.followthemoney.org/">Follow the Money</a>, as you mentioned) just <a href="http://www.macfound.org/maceirecipients/91/">won a MacArthur</a> for tracking campaign finance in all 50 states. They've got a pretty swell web interface for viewing state campaign finance data as well. What problems are we addressing that they aren't?

**Comment by Taitrnator** [comment]
@tarifhaque followthemoney.org is a great resource no doubt. I'd say we want to develop something that shows the influence of dark money, and the association between voting records and CFC contributions firsthand. Filtering and searching by every parameter is great, and thats fairly thorough in followthemoney (though often incomplete, as you'll see the majority of industry contributions in Alabama are labeled "uncoded"), but we'd like to be able to draw connections and bring candidates to the top of a list when they have a trend in dark money reception or voting for their PACs. In short, followthemoney focuses on all of the CFC issues, and we're concentrating on 3 or 4 CFC issues, the meat of the problem, if you will.

**Comment by tarifhaque** [comment]
@Taitrnator Gotcha. Seems we should focus on the specifics of associating dark money with candidates next? I think you've got another issue open with this as the subject matter.

**Comment by mleeds95** [comment]
@tarifhaque In addition to what @Taitrnator said, I'm hoping we can do a better job than them visualizing the data with interactive graphs.

**Comment by tarifhaque** [comment]
@Taitrnator @mleeds95 Saw this pretty infographic on Reddit today <i><a href="http://letsfreecongress.org/">Money wins Elections</a></i>. Definitely some good inspiration for the kinds of data viz we could do.

**Comment by mleeds95** [comment]
👏👍

**Comment by Taitrnator** [comment]
also theres this: http://granoproject.org/
