### ISSUE TITLE
Reduce data to state senators, representatives, governor, county, and justices

### ISSUE THREAD

**Issue by agrueneberg** [CodeforBirmingham/Open-Disclosure#73]
To determine which elected officials have sway in decision-making.

**Comment by mleeds95** [comment]
Would it make sense to keep all the data but emphasize the decision makers in the web interface?

**Comment by mleeds95** [comment]
If we want to make a whitelist or a blacklist here's all the unique offices:

STATE SENATOR
STATE REPRESENTATIVE
CIRCUIT COURT JUDGE
ATTORNEY GENERAL
GOVERNOR
DISTRICT COURT JUDGE
DISTRICT ATTORNEY
COUNTY COMMISSION CHAIR
COUNTY COMMISSIONER
REVENUE COMMISSIONER
STATE AUDITOR
STATE BOARD OF EDUCATION
SHERIFF
SECRETARY OF STATE
PUBLIC SERVICE COMMISSIONER
TAX ASSESSOR
LT. GOVERNOR
COURT OF CRIMINAL APPEALS JUDGE
LICENSE COMMISSIONER
SUPREME COURT ASSOCIATE JUSTICE
COUNTY SUPERINTENDENT OF EDUCATION
COMMISSIONER OF AGRICULTURE & INDUSTRIES
COURT OF CIVIL APPEALS JUDGE
STATE TREASURER
CIRCUIT CLERK
PROBATE JUDGE
PRESIDENT OF THE PUBLIC SERVICE COMMISSION
COUNTY BOARD OF EDUCATION
COUNTY CORONER
