### ISSUE TITLE
Re-Write Frontend

### ISSUE THREAD

**Issue by davidgrieser** [CodeforBirmingham/Open-Disclosure#83]
Simplified front end to use the base view from https://github.com/CodeforBirmingham/Open-Disclosure/issues/5

![profilemvp](https://cloud.githubusercontent.com/assets/292375/7898897/59b38970-06d4-11e5-83b3-fae7a20fbb44.png)

All initially expanded.

**Comment by agrueneberg** [comment]
We decided to not use Foundation Apps for reasons outlined in https://github.com/Taitrnator/OpenDisclosure-App/issues/1.

**Comment by agrueneberg** [comment]
Rewrite has been committed in dd7bb9faefbf799d2d14f101e7788df4ba67c014 and 1169d15f3dbbfd21d971f05203bd335d4d498a31. @Taitrnator will probably want to tweak the design a fair bit.

**Comment by Taitrnator** [comment]
I neglected to prototype the positions the candidates are running for but if its not too difficult I'd like to bind that info also. Stoked to see this finally working!

**Comment by agrueneberg** [comment]
The positions are displayed now, but I think we need to add some basic filtering and sorting facilities for the data to be useful.

**Comment by Taitrnator** [comment]
Absolutely, I'll work on it this evening

**Comment by agrueneberg** [comment]
Looks good now!
