### ISSUE TITLE
Improve repo organization

### ISSUE THREAD

**Issue by agrueneberg** [CodeforBirmingham/Open-Disclosure#88]
Currently the `master` branch contains the data pipeline and the `gh-pages` branch contains the frontend. @tarifhaque was looking for the frontend but couldn't find it. I'd suggest to reorganize the repo a little bit. There are several options:

1. Make `gh-pages` the default branch.
2. Have an empty `master` branch, move data pipeline into a separate branch, link from `master` branch to the two other branches.
3. Create an organization, have a separate repository for the data pipeline and and for the frontend.

What do you all think?

**Comment by tarifhaque** [comment]
Apparently it's Git custom to branch the repo for the project website, so I think we're okay.

**Comment by mleeds95** [comment]
We can explain where everything is in the main Readme.
