### ISSUE TITLE
Why are there two datasets for "Parties" in our Socrata data portal?

### ISSUE THREAD

**Issue by tarifhaque** [CodeforBirmingham/Open-Disclosure#90]
...and which one is the "correct" dataset?

**Comment by agrueneberg** [comment]
The correct (as in updated) one is [kjgr-g56d](https://brigades.opendatanetwork.com/dataset/Open-Disclosure-Alabama-Parties/kjgr-g56d). @mleeds95 should delete the other one.

Looking forward to seeing what you have planned for your analysis, @tarifhaque.

**Comment by tarifhaque** [comment]
Gotcha. Yeah, this one seems to have the party ID field populated.

**Comment by mleeds95** [comment]
Sorry for the confusion. I think I was testing something. It's gone now.
