### ISSUE TITLE
Reduce our impact on Socrata's servers.

### ISSUE THREAD

**Issue by mleeds95** [CodeforBirmingham/Open-Disclosure#92]
Instead of sending all the data to Socrata on each upload, why don't we only send data sets that have changed? In SendToSocrata.py we could take a hash of each file and only upload it if the hash has changed.

**Comment by agrueneberg** [comment]
I think the POST method relies on the full dataset to determine which
rows to add, which ones to update, and which ones to delete. If I
understand this change correctly, only the new or updated entries will
be sent to Socrata, and this might delete all the previous ones. Better
we double check.

**Comment by mleeds95** [comment]
No all the records are sent if any changed, but none are sent if none
changed. So it shouldn't delete any.

**Comment by agrueneberg** [comment]
Alright, great! Just wanted to make sure.

**Comment by agrueneberg** [comment]
Small issue when writing the hashes:
```
Traceback (most recent call last):
  File "SendToSocrata.py", line 115, in <module>
    main()
  File "SendToSocrata.py", line 78, in main  
    indent=4, separators=(',', ': '))
  File "/usr/lib/python3.4/json/__init__.py", line 178, in dump
    for chunk in iterable:
  File "/usr/lib/python3.4/json/encoder.py", line 422, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 429, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.4/json/encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'`t\x00\xf9\xb5\x02\x160n\r\xf4!<c\xc7\x8a' is not JSON serializable
```

**Comment by mleeds95** [comment]
It's fixed now. Sorry shouldn't have pushed that before testing it.

**Comment by agrueneberg** [comment]
Oh, of course, `digest` returns a binary representation. Sorry for
breaking and complaining about it. Must have been too hot at home :-)
