### ISSUE TITLE
Getting FEC Candidate IDs

### ISSUE THREAD

**Issue by tarifhaque** [CodeforBirmingham/Open-Disclosure#97]
To map candidates to "dark money" contributions from OpenSecrets, seems our Socrata data will need an additional piece of information, the "FECCandID" (FECCandID of recipient candidate). So we could add to the Python scripts to grab this for us, if possible. Or if the number of candidates is few, we can just do this manually, and pull the data for running candidates from OpenSecrets on a per candidate basis.

The data documentation for Open Secrets is here (will shed light on what data it provides and how it is relevant to our project):
http://www.opensecrets.org/resources/create/data_doc.php

**Comment by mleeds95** [comment]
As far as I can tell the FEC IDs only exist for Federal politicians not state-level ones.

**Comment by tarifhaque** [comment]
Yeah, you're correct. OpenSecrets only provides data for candidates running in federal elections. Data is sparse in that sense, but we could figure out how much dark money AL state Senators, like Shelby, are recieving.
